services:
  groupoffice:
    image: intermesh/groupoffice:latest
    restart: always
    ports:
      - "9000:80"
    links:
      - db
    volumes:
      - "godata:/var/lib/groupoffice:cached"
      - "goetc:/etc/groupoffice:cached"
#      - "gostudio:/usr/local/share/groupoffice/go/modules/studio:cached"
      - ./src/studio:/usr/local/share/groupoffice/go/modules/studio
    networks:
      - nginx-proxy-network

    #      Example for ssl
      - "./config/ssl/groupoffice:/etc/ssl/groupoffice"

    env_file:
      - ./db.env     
  db:
    image: mariadb:11.1.2
    restart: always    
    env_file:
      - ./db.env
    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - "dbdata:/var/lib/mysql:cached"
    networks:
      - nginx-proxy-network
volumes:
  godata:
  goetc:
  #gostudio:
  dbdata:

networks:
  nginx-proxy-network:
    external: true
